insert into car_table (car_model, car_release_year, car_color, car_company) values ('VS Commodore', 1997, 'Orange', 'Holden');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('TL', 2010, 'Turquoise', 'Acura');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Leone', 1986, 'Goldenrod', 'Subaru');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('E-350 Super Duty Van', 2006, 'Indigo', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('S2000', 2004, 'Orange', 'Honda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Continental', 1990, 'Blue', 'Lincoln');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('5 Series', 2007, 'Turquoise', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Familia', 1986, 'Crimson', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Monterey', 2005, 'Turquoise', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Town & Country', 1993, 'Blue', 'Chrysler');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Eclipse', 1995, 'Teal', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Pathfinder', 1995, 'Violet', 'Nissan');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Tracker', 2003, 'Crimson', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Escape', 2012, 'Turquoise', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Cutlass', 1998, 'Fuscia', 'Oldsmobile');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('C70', 2007, 'Red', 'Volvo');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Prizm', 1999, 'Pink', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Accent', 2010, 'Fuscia', 'Hyundai');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Laser', 1992, 'Crimson', 'Plymouth');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Special', 1962, 'Indigo', 'Buick');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('California', 2010, 'Aquamarine', 'Ferrari');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('944', 1991, 'Turquoise', 'Porsche');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('RL', 2000, 'Green', 'Acura');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Rodeo', 2002, 'Violet', 'Isuzu');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Dakota', 2009, 'Mauv', 'Dodge');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('QX', 1997, 'Pink', 'Infiniti');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Biturbo', 1984, 'Purple', 'Maserati');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Protege', 1997, 'Puce', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Silverado', 2009, 'Khaki', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Topaz', 1991, 'Aquamarine', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Q', 1995, 'Indigo', 'Infiniti');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('3500', 1994, 'Maroon', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('GS', 2004, 'Puce', 'Lexus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Navigator L', 2007, 'Yellow', 'Lincoln');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('MR2', 1993, 'Maroon', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('TL', 2007, 'Maroon', 'Acura');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('626', 1994, 'Goldenrod', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Mustang', 1968, 'Khaki', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Windstar', 1995, 'Green', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Xterra', 2005, 'Violet', 'Nissan');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Cabriolet', 1998, 'Fuscia', 'Volkswagen');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('MX-5', 2005, 'Yellow', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Exige', 2005, 'Turquoise', 'Lotus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('DTS', 2006, 'Maroon', 'Cadillac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Talon', 1992, 'Mauv', 'Eagle');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Caprice', 1992, 'Fuscia', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Starion', 1989, 'Aquamarine', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('XC70', 2005, 'Red', 'Volvo');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Santa Fe', 2004, 'Maroon', 'Hyundai');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Montana', 2004, 'Green', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('FJ Cruiser', 2012, 'Green', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('XK Series', 2000, 'Orange', 'Jaguar');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('RX', 2008, 'Khaki', 'Lexus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Cooper Clubman', 2011, 'Yellow', 'MINI');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Marquis', 1985, 'Pink', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Ascender', 2006, 'Purple', 'Isuzu');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Expedition', 2004, 'Crimson', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Safari', 2003, 'Red', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Aura', 2007, 'Khaki', 'Saturn');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Envoy', 2004, 'Violet', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Camaro', 1972, 'Purple', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Tribute', 2002, 'Green', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Continental', 2005, 'Teal', 'Bentley');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Express 1500', 1996, 'Aquamarine', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Acclaim', 1992, 'Green', 'Plymouth');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('F350', 2002, 'Mauv', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Fifth Ave', 1993, 'Turquoise', 'Chrysler');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Yukon XL 2500', 2012, 'Green', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('928', 1993, 'Red', 'Porsche');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('E-Class', 1993, 'Mauv', 'Mercedes-Benz');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('IS-F', 2012, 'Green', 'Lexus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Civic', 2003, 'Fuscia', 'Honda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('90', 1994, 'Maroon', 'Audi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Focus', 2007, 'Red', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Storm', 1992, 'Purple', 'Geo');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Stratus', 2000, 'Indigo', 'Dodge');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('GX', 2004, 'Goldenrod', 'Lexus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('A4', 1996, 'Goldenrod', 'Audi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Land Cruiser', 1995, 'Violet', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Esperante', 2005, 'Orange', 'Panoz');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Countach', 1990, 'Teal', 'Lamborghini');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Mustang', 1998, 'Mauv', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Rio', 2010, 'Khaki', 'Kia');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('GX', 2008, 'Khaki', 'Lexus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Touareg', 2007, 'Blue', 'Volkswagen');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Diablo', 1996, 'Violet', 'Lamborghini');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Concorde', 1997, 'Khaki', 'Chrysler');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Eclipse', 2005, 'Red', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Silverado 1500', 2006, 'Violet', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Frontier', 2007, 'Goldenrod', 'Nissan');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('X6', 2009, 'Indigo', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Ram Wagon B350', 1993, 'Puce', 'Dodge');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Sephia', 1998, 'Yellow', 'Kia');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Tracer', 1993, 'Maroon', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Caravan', 1997, 'Green', 'Dodge');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Rodeo', 2002, 'Orange', 'Isuzu');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Eclipse', 2010, 'Mauv', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Discovery', 2012, 'Red', 'Land Rover');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Oasis', 1999, 'Red', 'Isuzu');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Sebring', 1996, 'Orange', 'Chrysler');